from spark_jobs.common.schemas import (
    debezium_doctor_schema,
    debezium_patient_schema,
    debezium_slot_code_template_schema,
    debezium_doctor_slot_schema,
    debezium_appointment_schema,
    debezium_appointment_transaction_schema,
    debezium_medical_record_schema,
)

TABLE_CONFIGS = [
    {
        "name": "doctor",
        "topic": "healthcare.public.doctor",
        "schema": debezium_doctor_schema,
        "target_table": "stg_doctor",
        "checkpoint": "/tmp/checkpoints/stg_doctor",
        "pk": "doctor_id",
        "columns": [
            "doctor_id",
            "doctor_name",
            "specialty",
            "start_working_date",
        ],
    },
    {
        "name": "patient",
        "topic": "healthcare.public.patient",
        "schema": debezium_patient_schema,
        "target_table": "stg_patient",
        "checkpoint": "/tmp/checkpoints/stg_patient",
        "pk": "patient_id",
        "columns": [
            "patient_id",
            "patient_name",
            "address",
            "phone_number",
            "insurance_number",
            "date_of_birth",
            "gender",
            "email",
            "created_at",
            "updated_at",
        ],
    },
    {
        "name": "slot_code_template",
        "topic": "healthcare.public.slot_code_template",
        "schema": debezium_slot_code_template_schema,
        "target_table": "stg_slot_code_template",
        "checkpoint": "/tmp/checkpoints/stg_slot_code_template",
        "pk": "slot_code",
        "columns": [
            "slot_code",
            "start_time",
            "end_time",
            "display_order",
        ],
    },
    {
        "name": "doctor_slot",
        "topic": "healthcare.public.doctor_slot",
        "schema": debezium_doctor_slot_schema,
        "target_table": "stg_doctor_slot",
        "checkpoint": "/tmp/checkpoints/stg_doctor_slot",
        "pk": "slot_id",
        "columns": [
            "slot_id",
            "doctor_id",
            "slot_date",
            "slot_code",
            "slot_status",
        ],
    },
    {
        "name": "appointment",
        "topic": "healthcare.public.appointment",
        "schema": debezium_appointment_schema,
        "target_table": "stg_appointment",
        "checkpoint": "/tmp/checkpoints/stg_appointment",
        "pk": "appointment_id",
        "columns": [
            "appointment_id",
            "booking_ref",
            "slot_id",
            "patient_id",
            "booked_at",
        ],
    },
    {
        "name": "appointment_transaction",
        "topic": "healthcare.public.appointment_transaction",
        "schema": debezium_appointment_transaction_schema,
        "target_table": "stg_appointment_transaction",
        "checkpoint": "/tmp/checkpoints/stg_appointment_transaction",
        "pk": "transaction_id",
        "columns": [
            "transaction_id",
            "slot_id",
            "patient_id",
            "action",
            "created_at",
        ],
    },
    {
        "name": "medical_record",
        "topic": "healthcare.public.medical_record",
        "schema": debezium_medical_record_schema,
        "target_table": "stg_medical_record",
        "checkpoint": "/tmp/checkpoints/stg_medical_record",
        "pk": "record_id",
        "columns": [
            "record_id",
            "slot_id",
            "patient_id",
            "version_number",
            "diagnosis_note",
            "prescription_note",
            "created_at",
            "updated_at",
        ],
    },
]